


---
- name: Test playing around with the ansible_env var
  #connection: local
  hosts: all
  gather_facts: true
  tasks:
    - name: Setup
      setup:
        gather_subset:
          - "!all"
    
    - name: Test using ansible_env
      debug:
        msg: "{{ ansible_env }}"

    - name: Print Inventory ID 
      debug:
        msg: "{{ ansible_env.INVENTORY_ID }}"
