


#---
#- name: Test playing around with the ansible_env var
 # hosts: all
 # tasks:
---
- hosts: all
  tasks:
    - debug:
        msg: "{{ ansible_env }}"
    
    - name: Test using ansible_env
      debug:
        msg: "{{ ansible_env }}"

    - name: Print Inventory ID 
      debug:
        msg: "{{ ansible_env.INVENTORY_ID }}"
