---

- name: Test the fileglob filter
  hosts: server5
  gather_facts: false
  tasks:

    - name: Test with the fileglob plugin
      debug:
        msg: "{{query('fileglob', './files/*') }}"

    - name: use a loop
      debug:
        msg: "{{ item }}"
      loop: "{{query('fileglob', './files/*') }}"
