---
- name: Testing permissions on inventory
  hosts: all
  gather_facts: false
  tasks:

    - name: List installed ansible package
      yum:
        list: yum-utils
      register: result

    - name: Print result
      debug:
        var: result