---
- name: create vpc
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-1
    # prefix for naming
    prefix: staging
    # availability zone
    az1: us-east-1a

  vars_files: 
    - credentials.yml

  tasks:
    - name: create vpc
      ec2_vpc:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        cidr_block: 10.0.0.0/16
        resource_tags: '{"Name":"{{ prefix }}_vpc"}'
        subnets:
          - cidr: 10.0.0.0/24
            az: "{{ az1 }}"
            resource_tags: '{"Name":"{{ prefix }}_subnet_public"}'
        internet_gateway: yes
        route_tables:
          - subnets:
              - 10.0.0.0/24
            routes:
              - dest: 0.0.0.0/0
            gw: igw
      register: vpc

    - name: write vpc id to {{ prefix }}_vpc_info file
      shell: echo "{{ prefix }}"_vpc":" "{{ vpc.vpc_id }}"
            > "{{ prefix }}"_vpc_info
      delegate_to: rhel8vm1

    - name: write subnets id to {{ prefix }}_vpc_info file
      shell: echo "{{ item.resource_tags.Name }}"":" "{{ item.id }}"
            >> "{{ prefix }}"_vpc_info
      with_items: vpc.subnets
      delegate_to: rhel8vm1