---
- name: create key pair for EC2
  hosts: all
  gather_facts: true
  become: false
  vars_files: 
    - credentials.yml
  vars:
    #ansible_user_id: bforrest
    region: us-east-1
    keyname: aap-mesh-ec2
  tasks:
    - name: show user used by this play
      debug:
        var: ansible_user_id

    - name: create key pair
      ec2_key:
        region: "{{ region }}"
        name: "{{ keyname }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: mykey
      delegate_to: localhost

    - name: Print key pair 
      debug: var=mykey.key.private_key

    - name: Write to file 
      copy: 
        content: "{{ mykey.key.private_key }}" 
        dest: "/home/{{ ansible_user_id }}/.ssh/{{ keyname }}.pem"
        mode: 0600
      when: mykey.changed
      ignore_errors: true

    - name: show user used by this play
      debug:
        var: ansible_user_id