---
- name: Create RHEL 8 EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    #Your region
    region: us-east-1
  tasks:
    - name: EC2 basic provisioning
      ec2:
        region: "{{ region }}"
        key_name: aap-mesh-ec2
        instance_type: t2.micro
        image: ami-0b0af3577fe5e3532
        wait: yes
        group: aap_mesh_east
        instance_tags:
          group: mesh_east
        exact_count: 2
        count_tag:
          group: mesh_east