---
- name: Create RHEL 8 EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
    - ansible.builtin

  vars_files: 
    - credentials.yml
  vars:
    #Your region
    region: us-east-1
    sgname: AA-Lab
  tasks:

    - name: Gather VPC info
      ec2_vpc_subnet_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: subnetinfo

    - name: Gather Security Group information
      ec2_group_info:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: sginfo

    
    - name: Store vpc subnet fact
      set_fact:
        mysubnet: "{{ subnetinfo.subnets|map(attribute='subnet_id') | join(',')}}"

    - name: Store Security Group fact
      set_fact:
        mysg: "{{ sginfo.security_groups|map(attribute='group_id')|list }}"

    - name: EC2 basic provisioning
      ec2:
        image: ami-0b0af3577fe5e3532
        wait: yes
        instance_type: t2.xlarge
        region: "{{ region }}"
        group_id: "{{ mysg }}"
        vpc_subnet_id: "{{ mysubnet }}"
        key_name: aap-mesh-ec2
        count_tag:
          Name: AAPLab 
        exact_count: 2
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"