---
- name: create key pair for EC2
  hosts: localhost
  #connection: local
  gather_facts: no
  vars_files: 
    - credentials.yml
  vars:
    region: us-east-1
    keyname: aap-mesh-ec2
    #allow_world_readable_tmpfiles: true
    #admin_users: root
  tasks:
    - name: create key pair
      ec2_key:
        region: "{{ region }}"
        name: "{{ keyname }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: mykey

    - name: Print key pair 
      debug: var=mykey

    - name: whoami test
      shell: 'whoami'
      register: iam
      become_user: bforrest

    - name: Print who I am 
      debug: var=iam

    #- name: Write to file 
    #  copy: 
    #    content: "{{ mykey.key.private_key }}" 
    #    dest: "~/.ssh/{{ keyname }}.pem"
    #    mode: 0600
    #  when: mykey.changed
    #  become_user: bforrest