---
- name: Terminate RHEL 8 EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - credentials.yml
  vars:
    #Your region
    region: us-east-1
  tasks:
    - name: Terminate instances that were previously launched
      amazon.aws.ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'