---
- name: create vpc
  hosts: localhost
  connection: local
  gather_facts: no
  vars:

    region: us-east-1
    # availability zone - In this iteration this var is not used - 
    # az1: us-east-1a
    #VPC
    vpc_cidr: 10.0.0.0/24
    vpc_name: "Ben's Ansible Lab VPC"

    # Subnet
    subnet_name: "Ansible Lab Public Subnet"
    subnet_cidr: 10.10.0.0/26

    # Internet Gateway Name
    igw_name: "Ansible Lab IGW Traffic"

    securitygroup_name: "Ansible Lab Security Group"
    ec2_tag: "AAP2vpc"

  vars_files: 
    - credentials.yml

  tasks:
    - name: create vpc
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        state: present
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: vpc

   # - name: associate subnet to the VPC
   #   ec2_vpc_subnet:
   #     state: present
   #     vpc_id: 